# Generated by Django 3.2 on 2022-02-25 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=500)),
                ('about_me', models.CharField(max_length=500)),
                ('address_line_one', models.CharField(max_length=1000, null=True)),
                ('address_line_two', models.CharField(max_length=1000, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
