# Generated by Django 3.2 on 2022-02-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_line_one',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_two',
        ),
    ]
